language: node_js
node_js:
- '0.12'
before_script:
- npm install
script:
- npm test
after_script:
- npm run coveralls
notifications:
  hipchat:
    rooms:
      secure: Fabzq/EZfavXTdfeS/HuipESN8XuJnX1XYG1VjwqdyRCNAQUvRCCS+nje/KlbOua2kekQg8CUfoPCtE+CtBrgqF3SRmfj3TJVIrRx4/TmLjMKwHuHR0S+6lGX8Q2rFX5YlMe7xHJCOL01TWJqoCEIdb7KL7yVCmHA9lEonRK9I3Bdp2tyF9p0dcWDk5vHnbFwx1N8pb35Aa0TY+HTbU3NPuUKMJmEeYqLjkjAbI3tcOvyYSXZOiP3M7l3ady+gqVb4n4W9SyWQHpIwFZF/5Sg19KPPAfKtTKzkY8dQcga6NOl2gWauXIM3TkvK2FKXyr1XuA9VsHO118GLHq3twmC8TxceTLPR0wXlDQOjN7ANpV82mGsvpBWdI88hqtNr+YVBqSf+FxnY8Agdt7HYE1yxbqf1c27SdJpa+N049rKV5JZK3WzUUblrzq+TRSQRPjwWIfbgHt+oNIbpXwGLFa2gP5MmAvWqMQDiDgVzME6cSkfe2hK8Fp/RbdeyN7MOG1rjRaTHTG15MK80BbX0mnVx8cZsV7op++9Z4SPzbjqFtdn7bE8ze8j7d7neU28am5BZlDSnXB4+Jw51tMe32NV+YPwsqXR08Gv8RMVjhrrfcZ/+mSH6yYBVQ1bcohsczLnMnhx6mcUhYiW31U2L1tcfms8Gm9h7kBc7APZ0YhyOg=
env:
  global:
    secure: ETOwcjTT6SznImV28S9pXCKdJgX/23wWOP/ouK4rEy9nkgsp0Qm3NqzHf83Zb76R4Ooj30TYekyFhuET+5Xypjh5+/Gne/8AwW3l97oMcU/fgAHJUEERPEkTjuetR3464+g+V6Hx3U7LfWQd4tN+5/CniSZKYvGBH59/VYjoA/0qwPEo7R8nMLT8FyIMQ5aaSOW3MEjxr3/82PnPdDMkdSih5WbMbkAGt6RVN6Cw1Qq82zkJkjL4dyQ03D3AZvphQTEAvlPAnbhOXNzBCqeyB3hfQC9vZz8+WuNySEnZ2YYkAjlKDL/2TSg9RVvHqXodCMLqg0DRMRBLWxItFx6cIk82doqoN7r4KcqXnbkOTer0NAmiW48KC+5clxVTw+pbKf2HTxjweXhOvMnVu5Jn8OAaxysIZbj6dC4ikPhi0/Q7/K2KecSjDvBef3WvsrUu4aFZ9AL8/otFNZh+U3VLegllcjxl7lIq6x7Fb8WKjWwmZdsqtix6QDVk5lzAsN9PZkVcsLwAtvAqVs7/Wz4jtNGsPI7XjFtDUU/PG3WJSH+hTjEPhIxPwmizmmTs7VpKM7bO94PLVjIDNAzxXSGnkiiuu+SpMRpeGtr0EU87wYPIS7cNq9F0yz2svOAOsCpUKiZK8FmflUFD4y9Z2X3kbVx5cAzSP3OlPwJqN13+mjA=
